### ISSUE TITLE
Doesn't trigger the action when you open a PR not going through draft 

### ISSUE THREAD

**Issue by necojackarc** [necojackarc/request-review-based-on-files#5]
The README suggests that you should use:

```yaml
on:
  pull_request:
    types: [ready_for_review]
```

However, this doesn't trigger the action when you make a new PR without getting it to be a draft once.
Think about a better way to work on appropriate timings.

Possibly, we can add a new option - like `ignore_draft`.
At the same time, wouldn't it be nice to add `ignored_keywords`?
